  Resources:
    Api500Alarm:
      Type: AWS::CloudWatch::Alarm
      Properties:
        AlarmDescription: "Alarm if API responds with 500 to a 5% percentage of calls"
        Namespace: "AWS/ApiGateway"
        MetricName: 5XXError
        Dimensions:
        - Name: ApiName
          Value: ${{self:provider.stage}}-${{self:service}}
        Statistic: Average
        Period: 60
        EvaluationPeriods: 1
        Threshold: 0.05
        ComparisonOperator: GreaterThanThreshold

